export type SpecRow = {
  id: string;
  rule: string;
  ruleZh: string;
  ruleKo: string;
  section: string;
  impl: string;
  source: "wp" | "assumed";
};

export const SPEC: SpecRow[] = [
  {
    id: "one-signal",
    rule: "The only policy input is net ETH flow at the canonical pool — not volume, not trade count.",
    ruleZh: "政策唯一輸入是正規池的淨 ETH 流，不是成交量、也不是筆數。",
    ruleKo: "정책 입력은 정규 풀의 순 ETH 흐름뿐이다. 거래량도, 체결 수도 아니다.",
    section: "§4",
    impl: "netFlow(ethIn, ethOut)",
    source: "wp",
  },
  {
    id: "Fn",
    rule: "F_n = ETH_in − ETH_out for epoch n.",
    ruleZh: "第 n 期：F_n = 買入 ETH − 賣出 ETH。",
    ruleKo: "에포크 n: F_n = 매수 ETH − 매도 ETH.",
    section: "§4.1",
    impl: "netFlow",
    source: "wp",
  },
  {
    id: "signal",
    rule: "signal_n = F_{n-1} + F_{n-2}. Issuance moves on the signal.",
    ruleZh: "signal_n = F_{n-1} + F_{n-2}。發行倍率看這個，不看當期尖峰。",
    ruleKo: "signal_n = F_{n-1} + F_{n-2}. 발행 배수는 이것을 보고, 당기 스파이크는 보지 않는다.",
    section: "§4.1",
    impl: "policySignal",
    source: "wp",
  },
  {
    id: "fast-fees",
    rule: "Fee routing moves on sign(F_n) alone. Defence is the fast lever.",
    ruleZh: "Fee 路由只看 sign(F_n)。防衛是快槓桿。",
    ruleKo: "수수료 라우팅은 sign(F_n)만 본다. 방어가 빠른 레버다.",
    section: "§4 / §5",
    impl: "regimeOf(F_n)",
    source: "wp",
  },
  {
    id: "zero-is-contraction",
    rule: "Zero net flow is contraction, not expansion.",
    ruleZh: "淨流為零算收縮，不算擴張。",
    ruleKo: "순흐름이 0이면 수축이다. 확장이 아니다.",
    section: "§5",
    impl: "F > 0 ? expansion : contraction",
    source: "wp",
  },
  {
    id: "issuance",
    rule: "I_n = base × d × m_n, streamed pro rata to N branches.",
    ruleZh: "I_n = 基礎日發行 × 期長 × m_n，按分行數均分。",
    ruleKo: "I_n = 기초 일일 발행 × 기간 × m_n, N개 지점에 비례 배분.",
    section: "§5.1",
    impl: "issuance",
    source: "wp",
  },
  {
    id: "asymmetric-m",
    rule: "Cuts are immediate. Raises must be earned one epoch at a time.",
    ruleZh: "降息立刻砍；升息要連續正 signal、一次一步。",
    ruleKo: "인하는 즉시. 인상은 양수 시그널을 한 에포크에 한 칸씩 벌어야 한다.",
    section: "§5",
    impl: "nextMultiplier",
    source: "wp",
  },
  {
    id: "m-numbers",
    rule: "Floor, ceiling, step, launch m, epoch length are unpublished.",
    ruleZh: "m 上下限、步長、期長、基礎發行：白皮書留白，旋鈕上標 assumed。",
    ruleKo: "m 바닥·천장·스텝·기간·기초 발행은 미공개. 노브에 assumed로 표시.",
    section: "§5.2 / §14",
    impl: "params.mFloor … cutMode",
    source: "assumed",
  },
  {
    id: "supply",
    rule: "S_circ = 100M + M(t) − B(t). S_max = 1B − B(t).",
    ruleZh: "流通量 = 1 億 genesis + 提款鑄造 − 累計燒毀。上限隨燒下降。",
    ruleKo: "유통량 = 1억 제네시스 + 출금 민팅 − 누적 소각. 상한은 소각과 함께 내려간다.",
    section: "§3.1 / §3.2",
    impl: "supplies",
    source: "wp",
  },
  {
    id: "mint-on-exit",
    rule: "Issuance is a ledger credit. Tokens mint only on withdrawal.",
    ruleZh: "發行先入帳本；代幣只在退出時鑄造。",
    ruleKo: "발행은 먼저 원장 크레딧. 토큰은 출금 때만 민팅된다.",
    section: "§3 / §9",
    impl: "D += I_n; mint on exit",
    source: "wp",
  },
  {
    id: "pressure",
    rule: "P = W / max(D + W, ε) over a trailing 7-day window.",
    ruleZh: "退出壓力 P = 近 7 日提款 / max(留下 + 提款, ε)。",
    ruleKo: "이탈 압력 P = 최근 7일 출금 / max(잔류 + 출금, ε).",
    section: "§9.1",
    impl: "exitPressure",
    source: "wp",
  },
  {
    id: "quadratic-fee",
    rule: "Resolution fee is a quadratic from floor to ceiling, saturating at a pressure threshold.",
    ruleZh: "Resolution fee 是二次曲線，從地板到天花板，在飽和壓力處封頂。",
    ruleKo: "Resolution fee는 바닥에서 천장까지 이차 곡선. 포화 압력에서 캡.",
    section: "§9.1",
    impl: "resolutionFee",
    source: "wp",
  },
  {
    id: "fee-numbers",
    rule: "Floor, ceiling, saturation point unpublished. Ceiling must be < 70% revocation.",
    ruleZh: "地板 / 天花板 / 飽和點留白。天花板必須低於 70% 撤銷費。",
    ruleKo: "바닥 / 천장 / 포화점은 미공개. 천장은 70% 철회 수수료보다 낮아야 한다.",
    section: "§9 / §10 / §14",
    impl: "feeFloor, feeCeiling=35%, pressureSat",
    source: "assumed",
  },
  {
    id: "half-half",
    rule: "Half of every resolution fee is burned. The other half is paid to bankers who stayed.",
    ruleZh: "退出費一半燒毀，一半付給留下的人。",
    ruleKo: "이탈 수수료 절반은 소각, 절반은 남은 사람에게.",
    section: "§9",
    impl: "splitResolution",
    source: "wp",
  },
  {
    id: "never-pause",
    rule: "Withdrawals are never paused or queued. Price is the only control.",
    ruleZh: "提款從不暫停、不排隊。唯一控制是價格。",
    ruleKo: "출금은 멈추지 않고, 대기열도 없다. 유일한 통제는 가격.",
    section: "§9",
    impl: "exits always execute",
    source: "wp",
  },
  {
    id: "split",
    rule: "All protocol ETH splits 70% active vault / 15% POL / 15% team.",
    ruleZh: "協議 ETH 一律 70 / 15 / 15。",
    ruleKo: "프로토콜 ETH는 항상 70 / 15 / 15.",
    section: "§11",
    impl: "splitProtocolEth",
    source: "wp",
  },
  {
    id: "vaults",
    rule: "Expansion vault buys gold and cannot sell. Contraction vault buys and burns.",
    ruleZh: "擴張金庫買金且永不賣。收縮金庫回購並燒毀。",
    ruleKo: "확장 볼트는 금을 사고 팔지 않는다. 수축 볼트는 사서 소각한다.",
    section: "§11",
    impl: "regime branch in stepEpoch",
    source: "wp",
  },
  {
    id: "buyback",
    rule: "spend_tick = min(0.10 × V, 0.002 × R) hourly ≈ 5% of pool depth / day.",
    ruleZh: "每小時回購 min(10% 金庫, 0.2% 池深)，一天約 5% 池深。",
    ruleKo: "시간당 바이백 min(볼트 10%, 풀 깊이 0.2%). 하루 약 풀 깊이 5%.",
    section: "§11.1",
    impl: "buybackTick",
    source: "wp",
  },
  {
    id: "revocation",
    rule: "Dormant 30d → 2% bounty (cap 100k) → 70% revocation, half burn half stayers.",
    ruleZh: "休眠 30 天可檢舉：賞金 2%（上限 10 萬），撤銷費 70%，半燒半給留下的人。",
    ruleKo: "30일 휴면이면 신고: 현상금 2%(상한 10만), 철회 70%, 반 소각 반 잔류자.",
    section: "§10",
    impl: "bounty / revocationFee",
    source: "wp",
  },
  {
    id: "license-curve",
    rule: "P(t) = P_start × (P_floor / P_start)^{t/24h}. License open is 2× last; charter open is 3×.",
    ruleZh: "荷蘭拍指數衰減。牌照開盤 2 倍昨收，特許開盤 3 倍。",
    ruleKo: "더치 옥션은 지수 감쇠. 라이선스 시초가 전일 2배, 차터 시초가 3배.",
    section: "§7.1 / §8",
    impl: "licensePrice",
    source: "wp",
  },
];
